version: '3'
services:
  db:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=pass
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=local -password=pass -connectRetries=60 migrate
    volumes:
      - ./db:/flyway/sql
    depends_on:
      - db
