package com.example.domabatchinsert.orverride;

import org.seasar.doma.jdbc.entity.EntityType;
import org.seasar.doma.jdbc.id.IdGenerationConfig;
import org.seasar.doma.jdbc.id.ReservedIdProvider;
import org.seasar.doma.jdbc.query.AutoBatchInsertQuery;

public class CustomAutoBatchInsertQuery<ENTITY>  extends AutoBatchInsertQuery<ENTITY>  {
  public CustomAutoBatchInsertQuery(EntityType entityType) {
    super(entityType);
  }

  @Override
  protected void prepareIdAndVersionPropertyTypes() {
    generatedIdPropertyType = entityType.getGeneratedIdPropertyType();
    if (generatedIdPropertyType != null) {
      if (idGenerationConfig == null) {
        if (generatedKeysIgnored) {
          idGenerationConfig = new IdGenerationConfig(config, entityType);
        } else {
          idGenerationConfig =
              new IdGenerationConfig(
                  config, entityType, new ReservedIdProvider(config, entityType, entities.size()));
        }
        generatedIdPropertyType.validateGenerationStrategy(idGenerationConfig);
        autoGeneratedKeysSupported =
            !generatedKeysIgnored
                && generatedIdPropertyType.isAutoGeneratedKeysSupported(idGenerationConfig);
        batchSupported =
            generatedKeysIgnored || generatedIdPropertyType.isBatchSupported(idGenerationConfig);
      }
    }
  }
}
